# Generated by Django 3.2.3 on 2021-08-29 15:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('iteachsgm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
